services:
  frontend:
    build:
      context: ./deepshield-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_WEBSOCKET_URL=ws://backend:8000/ws
    depends_on:
      - backend

  backend:
    build:
      context: ./deepshield-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/deepshield
      - INSTAGRAM_APP_ID=${INSTAGRAM_APP_ID}
      - INSTAGRAM_APP_SECRET=${INSTAGRAM_APP_SECRET}
      - INSTAGRAM_ACCESS_TOKEN=${INSTAGRAM_ACCESS_TOKEN}
      - MODEL_CACHE_DIR=/app/model_cache
      - DATASET_DIR=/app/datasets
      - TRANSFORMERS_CACHE=/app/model_cache/transformers
      - TORCH_HOME=/app/model_cache/torch
      - PYTHONPATH=/app
    volumes:
      - ai_model_cache:/app/model_cache
      - datasets:/app/datasets
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  ai_model_cache:
    driver: local
  datasets:
    driver: local
