services:
  # Backend Service
  - type: web
    name: deepshield-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      cd deepshield-backend && pip install -r requirements.txt
      mkdir -p /opt/render/project/src/datasets
      curl -L https://github.com/ondyari/FaceForensics/raw/master/dataset/FaceForensics++ -o /opt/render/project/src/datasets/faceforensics.zip
      curl -L https://github.com/notAI-tech/NudeNet/raw/v2/dataset/nude.zip -o /opt/render/project/src/datasets/nudenet.zip
      curl -L https://huggingface.co/datasets/hatexplain/raw/main/dataset.zip -o /opt/render/project/src/datasets/hatexplain.zip
    startCommand: cd deepshield-backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://deepshield:deepshield@cluster0.mongodb.net/deepshield?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: deepshield-production-secret-key-2024
      - key: INSTAGRAM_APP_ID
        value: 1112199003401971
      - key: INSTAGRAM_APP_SECRET
        value: 33191e18dd0aa8db81049ee756d2f324
      - key: INSTAGRAM_ACCESS_TOKEN
        value: IGAAPzigKEbvNBZAE1pMG9uUTZAxR0NzSTRIdEE5SXNhc0hRMHVZAWWhsNjcxSzVUa2w1ZAHFyYmNoLVU3bXJvZA0N5YUdhWC1nN2V0WWtoSHJMS3ZAPTFB6am82SFZAwSG1uUXNJcU1hUDkxSFdVa2t4Tl9zbDNQcElTNGtkTmRVWkZADZAwZDZD
      - key: INSTAGRAM_ACCOUNT_ID
        value: 17841451799717870
      - key: DATASET_DIR
        value: /opt/render/project/src/datasets
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: "1"
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/src/.cache/huggingface

  # Frontend Service
  - type: web
    name: deepshield-frontend
    env: node
    buildCommand: cd deepshield-frontend && npm install && npm run build
    startCommand: cd deepshield-frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://deepshield-backend.onrender.com
      - key: VITE_INSTAGRAM_APP_ID
        value: 1112199003401971
